//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniblog.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miniblog.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bad request: The request cannot be fulfilled due to bad syntax 的本地化字符串。
        /// </summary>
        public static string BadRequestTheRequestCannotBeFulfilledDueToBadSyntax {
            get {
                return ResourceManager.GetString("BadRequestTheRequestCannotBeFulfilledDueToBadSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forbidden 的本地化字符串。
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Server Error - server was unable to finish processing the request 的本地化字符串。
        /// </summary>
        public static string InternalServerErrorServerWasUnableToFinishProcessingTheRequest {
            get {
                return ResourceManager.GetString("InternalServerErrorServerWasUnableToFinishProcessingTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miniblog.Core 的本地化字符串。
        /// </summary>
        public static string MiniblogCore {
            get {
                return ResourceManager.GetString("MiniblogCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New post 的本地化字符串。
        /// </summary>
        public static string NewPost {
            get {
                return ResourceManager.GetString("NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline 的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page not found 的本地化字符串。
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by 的本地化字符串。
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in 的本地化字符串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in as administrator 的本地化字符串。
        /// </summary>
        public static string SignInAsAdministrator {
            get {
                return ResourceManager.GetString("SignInAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign in to the website 的本地化字符串。
        /// </summary>
        public static string SignInToTheWebsite {
            get {
                return ResourceManager.GetString("SignInToTheWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out 的本地化字符串。
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign out as administrator 的本地化字符串。
        /// </summary>
        public static string SignOutAsAdministrator {
            get {
                return ResourceManager.GetString("SignOutAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some features of this website do not work as expected when JavaScript is disabled 的本地化字符串。
        /// </summary>
        public static string SomeFeaturesOfThisWebsiteDoNotWorkAsExpectedWhenJavaScriptIsDisabled {
            get {
                return ResourceManager.GetString("SomeFeaturesOfThisWebsiteDoNotWorkAsExpectedWhenJavaScriptIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 That’s odd... Something we didn&apos;t expect happened 的本地化字符串。
        /// </summary>
        public static string ThatsOddSomethingWeDidntExpectHappened {
            get {
                return ResourceManager.GetString("ThatsOddSomethingWeDidntExpectHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The page you requested can not be shown because you are offline. 的本地化字符串。
        /// </summary>
        public static string ThePageYouRequestedCanNotBeShownBecauseYouAreOffline {
            get {
                return ResourceManager.GetString("ThePageYouRequestedCanNotBeShownBecauseYouAreOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The server timed out waiting for the request 的本地化字符串。
        /// </summary>
        public static string TheServerTimedOutWaitingForTheRequest {
            get {
                return ResourceManager.GetString("TheServerTimedOutWaitingForTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unauthorized 的本地化字符串。
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password is invalid. 的本地化字符串。
        /// </summary>
        public static string UsernameOrPasswordIsInvalid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsInvalid", resourceCulture);
            }
        }
    }
}
